version: '3.8'

services:
  agent-orchestrator:
    build: 
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    depends_on:
      - ollama
    volumes:
      - ./app:/app
      - /app/__pycache__
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data_dev:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_DEBUG=1

volumes:
  ollama_data_dev: