version: '3.8'

services:
  agent-orchestrator:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - DEBUG=false
      - LOG_LEVEL=INFO
    depends_on:
      - ollama
    restart: unless-stopped
    
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data_prod:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    restart: unless-stopped

volumes:
  ollama_data_prod: